/**
 * Supabase Database Types
 *
 * NOTE: This file is auto-generated by `pnpm --filter @repo/database supabase:gen`
 * when a local Supabase instance is available. Until then, minimal stubs are
 * provided to satisfy TypeScript compilation.
 *
 * For full type coverage, see src/manual-types.ts which contains manually
 * maintained type definitions for tables that exist in migrations.
 */

// Minimal Database interface stub - actual tables/views are in manual-types.ts
// When supabase:gen runs successfully, this will be replaced with full definitions
export interface Database {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
  };
}
