#!/usr/bin/env node

/**
 * Arch-System Automated Version Manager
 *
 * Provides single-source-of-truth semantic versioning across the federated workspace,
 * synchronizing root package.json, apps/portal/package.json, version.json, and
 * auto-generating build-time version constants (apps/portal/lib/version.generated.ts).
 *
 * Usage:
 *   node tools/scripts/version-manager.mjs sync
 *   node tools/scripts/version-manager.mjs bump [major|minor|patch|premajor|preminor|prepatch|<version>]
 *   node tools/scripts/version-manager.mjs status
 */

import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '../..');

const ROOT_PKG_PATH = path.join(REPO_ROOT, 'package.json');
const PORTAL_PKG_PATH = path.join(REPO_ROOT, 'apps/portal/package.json');
const VERSION_JSON_PATH = path.join(REPO_ROOT, 'version.json');
const PORTAL_VERSION_GEN_PATH = path.join(REPO_ROOT, 'apps/portal/lib/version.generated.ts');
const CHANGELOG_PATH = path.join(REPO_ROOT, 'CHANGELOG.md');

function getGitInfo() {
  try {
    const full = execSync('git rev-parse HEAD', { cwd: REPO_ROOT, encoding: 'utf8' }).trim();
    const short = execSync('git rev-parse --short HEAD', {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }).trim();
    const branch =
      execSync('git branch --show-current', { cwd: REPO_ROOT, encoding: 'utf8' }).trim() || 'main';
    return { full, short, branch };
  } catch {
    return {
      full: process.env.VERCEL_GIT_COMMIT_SHA || 'unknown_sha',
      short: (process.env.VERCEL_GIT_COMMIT_SHA || 'unknown').slice(0, 7),
      branch: process.env.VERCEL_GIT_COMMIT_REF || 'main',
    };
  }
}

function parseSemver(v) {
  const match = v.match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/);
  if (!match) return null;
  return {
    major: parseInt(match[1], 10),
    minor: parseInt(match[2], 10),
    patch: parseInt(match[3], 10),
    prerelease: match[4] || null,
  };
}

function incrementSemver(current, type) {
  const parsed = parseSemver(current);
  if (!parsed) {
    throw new Error(`Cannot parse current version "${current}" as semver.`);
  }

  const { major, minor, patch } = parsed;
  switch (type) {
    case 'major':
      return `${major + 1}.0.0`;
    case 'minor':
      return `${major}.${minor + 1}.0`;
    case 'patch':
      return `${major}.${minor}.${patch + 1}`;
    case 'premajor':
      return `${major + 1}.0.0-rc.0`;
    case 'preminor':
      return `${major}.${minor + 1}.0-rc.0`;
    case 'prepatch':
      return `${major}.${minor}.${patch + 1}-rc.0`;
    default:
      if (/^\d+\.\d+\.\d+/.test(type)) {
        return type;
      }
      throw new Error(
        `Unknown bump type: ${type}. Choose major, minor, patch, or explicit version.`
      );
  }
}

function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, data) {
  writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

export function syncVersion(options = {}) {
  const rootPkg = readJson(ROOT_PKG_PATH);
  const targetVersion = options.targetVersion || rootPkg.version || '2.0.0';
  const git = getGitInfo();
  const timestamp = new Date().toISOString();
  const releaseName = `Arch OS v${targetVersion} // Industrial Command`;
  const systemCodename = 'Industrial Telemetry Bus';

  // 1. Sync Root package.json
  if (rootPkg.version !== targetVersion) {
    rootPkg.version = targetVersion;
    writeJson(ROOT_PKG_PATH, rootPkg);
  }

  // 2. Sync Portal package.json
  if (existsSync(PORTAL_PKG_PATH)) {
    const portalPkg = readJson(PORTAL_PKG_PATH);
    if (portalPkg.version !== targetVersion) {
      portalPkg.version = targetVersion;
      writeJson(PORTAL_PKG_PATH, portalPkg);
    }
  }

  // 3. Write version.json (Root SSoT)
  const versionData = {
    version: targetVersion,
    gitCommit: git.short,
    gitCommitFull: git.full,
    gitBranch: git.branch,
    buildTimestamp: timestamp,
    releaseName,
    systemCodename,
  };
  writeJson(VERSION_JSON_PATH, versionData);

  // 4. Generate apps/portal/lib/version.generated.ts
  const generatedTs = `// AUTO-GENERATED by tools/scripts/version-manager.mjs — DO NOT EDIT DIRECTLY
export const APP_VERSION = '${targetVersion}';
export const GIT_COMMIT_SHA = '${git.short}';
export const GIT_COMMIT_FULL = '${git.full}';
export const GIT_BRANCH = '${git.branch}';
export const BUILD_TIMESTAMP = '${timestamp}';
export const RELEASE_NAME = '${releaseName}';
export const SYSTEM_CODENAME = '${systemCodename}';
`;
  writeFileSync(PORTAL_VERSION_GEN_PATH, generatedTs, 'utf8');

  console.log(`✅ Automated Versioning Synced: v${targetVersion} (${git.short})`);
  return versionData;
}

export function bumpVersion(type, options = {}) {
  const rootPkg = readJson(ROOT_PKG_PATH);
  const currentVersion = rootPkg.version || '2.0.0';
  const nextVersion = incrementSemver(currentVersion, type);

  console.log(`🚀 Bumping version from v${currentVersion} -> v${nextVersion} (${type})`);

  // Sync everything to new version
  const versionData = syncVersion({ targetVersion: nextVersion });

  // Update CHANGELOG.md if requested
  if (options.changelog && existsSync(CHANGELOG_PATH)) {
    const git = getGitInfo();
    const dateStr = new Date().toISOString().split('T')[0];
    const changelogEntry = `\n## [${nextVersion}] - ${dateStr}\n- Automated release bump (${type})\n- Commit: ${git.short}\n`;
    const existingChangelog = readFileSync(CHANGELOG_PATH, 'utf8');
    writeFileSync(
      CHANGELOG_PATH,
      existingChangelog.replace('# Changelog\n', `# Changelog\n${changelogEntry}`),
      'utf8'
    );
    console.log(`📝 Updated CHANGELOG.md with release v${nextVersion}`);
  }

  // Create git tag if requested
  if (options.tag) {
    try {
      execSync(`git tag -a v${nextVersion} -m "Release v${nextVersion}"`, {
        cwd: REPO_ROOT,
        stdio: 'inherit',
      });
      console.log(`🏷️  Created git tag v${nextVersion}`);
    } catch (err) {
      console.warn(`⚠️  Failed to create git tag: ${err.message}`);
    }
  }

  return versionData;
}

export function printStatus() {
  const rootPkg = readJson(ROOT_PKG_PATH);
  const git = getGitInfo();
  let portalVersion = 'missing';
  if (existsSync(PORTAL_PKG_PATH)) {
    portalVersion = readJson(PORTAL_PKG_PATH).version;
  }

  console.log('--- Arch-System Automated Version Status ---');
  console.log(`Root Version:      v${rootPkg.version}`);
  console.log(`Portal Version:    v${portalVersion}`);
  console.log(`Git Commit:        ${git.short} (${git.full})`);
  console.log(`Git Branch:        ${git.branch}`);
  console.log(`In Sync:           ${rootPkg.version === portalVersion ? 'YES ✅' : 'NO ❌'}`);
  console.log('--------------------------------------------');
}

// CLI Execution entrypoint
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const command = process.argv[2] || 'status';
  const arg = process.argv[3];
  const withTag = process.argv.includes('--tag');
  const withChangelog = process.argv.includes('--changelog');

  if (command === 'sync') {
    syncVersion();
  } else if (command === 'bump') {
    if (!arg) {
      console.error('Error: bump requires an argument: major, minor, patch, or version');
      process.exit(1);
    }
    bumpVersion(arg, { tag: withTag, changelog: withChangelog });
  } else if (command === 'status') {
    printStatus();
  } else {
    console.error(`Unknown command: ${command}. Use sync, bump, or status.`);
    process.exit(1);
  }
}
