-- Shift Completeness Alerts Table
-- Stores alerts generated by the shift completeness check job
-- when machines are missing entries >30 minutes into a shift

CREATE TABLE IF NOT EXISTS shift_completeness_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  department_id UUID NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  shift_date DATE NOT NULL,
  shift_type TEXT NOT NULL CHECK (shift_type IN ('day', 'night')),
  missing_machine_count INTEGER NOT NULL DEFAULT 0,
  missing_machines TEXT,
  minutes_into_shift INTEGER NOT NULL,
  resolved BOOLEAN NOT NULL DEFAULT false,
  resolved_at TIMESTAMPTZ,
  resolved_by UUID REFERENCES employees(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Ensure we don't create duplicate alerts for the same department/shift/date
  CONSTRAINT unique_shift_alert UNIQUE (department_id, shift_date, shift_type, resolved)
);

-- Create index for efficient querying of unresolved alerts
CREATE INDEX IF NOT EXISTS idx_shift_completeness_alerts_unresolved 
  ON shift_completeness_alerts(department_id, shift_date, resolved) 
  WHERE resolved = false;

-- Create index for time-based queries
CREATE INDEX IF NOT EXISTS idx_shift_completeness_alerts_created_at 
  ON shift_completeness_alerts(created_at DESC);

-- Add RLS policies
ALTER TABLE shift_completeness_alerts ENABLE ROW LEVEL SECURITY;

-- Service role can do everything (for background jobs)
CREATE POLICY "Service role full access on shift_completeness_alerts"
  ON shift_completeness_alerts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Admins can read and resolve alerts
CREATE POLICY "Admins can read shift_completeness_alerts"
  ON shift_completeness_alerts
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM employees e
      WHERE e.auth_id = auth.uid()
      AND e.role = 'admin'
    )
  );

CREATE POLICY "Admins can resolve shift_completeness_alerts"
  ON shift_completeness_alerts
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM employees e
      WHERE e.auth_id = auth.uid()
      AND e.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employees e
      WHERE e.auth_id = auth.uid()
      AND e.role = 'admin'
    )
  );

-- Department members can read alerts for their department
CREATE POLICY "Department members can read their shift_completeness_alerts"
  ON shift_completeness_alerts
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM employees e
      WHERE e.auth_id = auth.uid()
        AND (
          e.department_id = shift_completeness_alerts.department_id
          OR shift_completeness_alerts.department_id = ANY(e.accessible_departments)
          OR e.role = 'admin'
        )
    )
  );

-- Add comment
COMMENT ON TABLE shift_completeness_alerts IS 'Stores alerts generated by automated shift completeness checks';
COMMENT ON COLUMN shift_completeness_alerts.minutes_into_shift IS 'How many minutes into the shift when the alert was generated';
COMMENT ON COLUMN shift_completeness_alerts.missing_machines IS 'Comma-separated list of machine names missing entries';
