-- Shift Integrity Reports Table
-- Stores weekly shift integrity reports generated by automated jobs
-- Includes metrics on shift completion, data quality, and operational KPIs

CREATE TABLE IF NOT EXISTS shift_integrity_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_data JSONB NOT NULL,
  report_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Ensure only one report per date
  CONSTRAINT unique_report_date UNIQUE (report_date)
);

-- Create index for time-based queries
CREATE INDEX IF NOT EXISTS idx_shift_integrity_reports_date 
  ON shift_integrity_reports(report_date DESC);

-- Add RLS policies
ALTER TABLE shift_integrity_reports ENABLE ROW LEVEL SECURITY;

-- Service role can do everything (for background jobs)
CREATE POLICY "Service role full access on shift_integrity_reports"
  ON shift_integrity_reports
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Admins can read reports
CREATE POLICY "Admins can read shift_integrity_reports"
  ON shift_integrity_reports
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM employees e
      WHERE e.auth_id = auth.uid()
      AND e.role = 'admin'
    )
  );

-- Add comment
COMMENT ON TABLE shift_integrity_reports IS 'Stores weekly shift integrity reports with metrics on completion, data quality, and operational KPIs';
COMMENT ON COLUMN shift_integrity_reports.report_data IS 'JSONB containing all report metrics (shift_metrics, data_quality, data_integrity, operational_kpis)';
