#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# SSL Certificate Setup Script for Arch-Systems
# PURPOSE: Automate Let's Encrypt SSL certificate acquisition and renewal
# USAGE: ./scripts/setup-ssl.sh <domain> <email>
# EXAMPLE: ./scripts/setup-ssl.sh portal.plantcor.os admin@plantcor.os
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
NGINX_DIR="$REPO_ROOT/config/nginx"
CERTS_DIR="$REPO_ROOT/config/certs"
LOG_FILE="$REPO_ROOT/logs/ssl-setup-$(date +%Y%m%d-%H%M%S).log"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() {
    echo -e "${GREEN}[SSL]${NC} $*" | tee -a "$LOG_FILE"
}

info() {
    echo -e "${CYAN}[INFO]${NC} $*" | tee -a "$LOG_FILE"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $*" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"
}

# ── Prerequisites Check ──────────────────────────────────────────────────────
check_prerequisites() {
    log "Checking prerequisites..."

    local missing=0

    # Check Docker
    if ! command -v docker &> /dev/null; then
        error "Docker is not installed"
        missing=1
    fi

    # Check domain provided
    if [ -z "${1:-}" ]; then
        error "Domain name is required"
        echo "Usage: $0 <domain> <email>"
        exit 1
    fi

    # Check email provided
    if [ -z "${2:-}" ]; then
        error "Email address is required"
        echo "Usage: $0 <domain> <email>"
        exit 1
    fi

    # Check port 80 is available
    if command -v ss &> /dev/null; then
        if ss -tlnp | grep -q ':80 '; then
            warn "Port 80 is already in use - Certbot standalone mode may fail"
            warn "Consider using DNS challenge instead"
        fi
    fi

    if [ $missing -eq 1 ]; then
        exit 1
    fi

    log "Prerequisites check passed"
}

# ── Directory Setup ──────────────────────────────────────────────────────────
setup_directories() {
    log "Creating required directories..."

    mkdir -p "$NGINX_DIR/conf.d"
    mkdir -p "$CERTS_DIR"
    mkdir -p "$REPO_ROOT/logs"
    mkdir -p "$REPO_ROOT/volumes/certbot/www"
    mkdir -p "$REPO_ROOT/volumes/certbot/conf"

    log "Directories created"
}

# ── Nginx Configuration ──────────────────────────────────────────────────────
create_nginx_ssl_config() {
    local domain="$1"
    local config_file="$NGINX_DIR/conf.d/ssl.conf"

    log "Creating Nginx SSL configuration for $domain..."

    cat > "$config_file" << EOF
# SSL Configuration for $domain
# Auto-generated by setup-ssl.sh on $(date -Iseconds)

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name $domain;

    # ACME challenge location for Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all other HTTP to HTTPS
    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS Server
server {
    listen 443 ssl http2;
    server_name $domain;

    # SSL Certificate paths
    ssl_certificate /etc/nginx/certs/$domain/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/$domain/privkey.pem;

    # SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'self';" always;

    # SSL Buffer
    ssl_buffer_size 4k;

    # Logging
    access_log /var/log/nginx/${domain}-access.log;
    error_log /var/log/nginx/${domain}-error.log;

    # Proxy to portal backend
    location / {
        proxy_pass http://portal:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Buffering
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
    }

    # Health check endpoint
    location /api/health {
        proxy_pass http://portal:3000/api/health;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        access_log off;
    }

    # Rate limiting zone
    limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=10r/s;

    # Apply rate limiting to API routes
    location /api/ {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://portal:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
EOF

    log "Nginx SSL configuration created: $config_file"
}

# ── Certificate Acquisition ──────────────────────────────────────────────────
obtain_certificate() {
    local domain="$1"
    local email="$2"

    log "Obtaining SSL certificate for $domain..."

    # Create directory for this domain's certs
    mkdir -p "$CERTS_DIR/$domain"

    # Run Certbot in standalone mode (requires port 80 to be free)
    # If port 80 is in use, use DNS challenge instead
    docker run --rm \
        -v "$CERTS_DIR:/etc/letsencrypt" \
        -v "$REPO_ROOT/volumes/certbot/www:/var/www/certbot" \
        certbot/certbot certonly \
        --webroot \
        --webroot-path=/var/www/certbot \
        --email "$email" \
        --agree-tos \
        --no-eff-email \
        --force-renewal \
        -d "$domain" \
        --key-type ecdsa

    if [ $? -eq 0 ]; then
        log "Certificate obtained successfully"

        # Create symlink for Nginx
        ln -sf "/etc/letsencrypt/live/$domain" "$CERTS_DIR/$domain" 2>/dev/null || true

        log "Certificate location: $CERTS_DIR"
    else
        error "Failed to obtain certificate"
        error ""
        error "TROUBLESHOOTING:"
        error "1. Ensure port 80 is not in use by another service"
        error "2. Ensure domain DNS points to this server"
        error "3. For DNS challenge, run:"
        error "   docker run --rm -v $CERTS_DIR:/etc/letsencrypt certbot/certbot certonly \\"
        error "     --dns-cloudflare \\"
        error "     --dns-cloudflare-credentials /path/to/credentials.ini \\"
        error "     -d $domain"
        exit 1
    fi
}

# ── Certificate Renewal Setup ───────────────────────────────────────────────
setup_auto_renewal() {
    local domain="$1"

    log "Setting up automatic certificate renewal..."

    # Create renewal script
    cat > "$SCRIPT_DIR/renew-ssl.sh" << 'EOF'
#!/bin/bash
# SSL Certificate Renewal Script
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
CERTS_DIR="$REPO_ROOT/config/certs"
LOG_FILE="$REPO_ROOT/logs/ssl-renewal-$(date +%Y%m%d).log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "Starting SSL certificate renewal check..."

# Attempt renewal (Certbot only renews if <30 days from expiry)
docker run --rm \
    -v "$CERTS_DIR:/etc/letsencrypt" \
    -v "$REPO_ROOT/volumes/certbot/www:/var/www/certbot" \
    certbot/certbot renew \
    --webroot \
    --webroot-path=/var/www/certbot \
    --quiet

RENEWAL_STATUS=$?

if [ $RENEWAL_STATUS -eq 0 ]; then
    log "Renewal check completed successfully"

    # Check if any certificates were actually renewed
    if docker run --rm \
        -v "$CERTS_DIR:/etc/letsencrypt" \
        certbot/certbot renew \
        --dry-run \
        --quiet 2>&1 | grep -q "No renewals were due"; then
        log "No certificates due for renewal"
    else
        log "Certificates renewed - reloading Nginx..."

        # Reload Nginx to pick up new certificates
        docker exec arch-nginx nginx -s reload 2>/dev/null || true

        log "Nginx reloaded with new certificates"
    fi
else
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Renewal failed" | tee -a "$LOG_FILE"
    exit 1
fi
EOF

    chmod +x "$SCRIPT_DIR/renew-ssl.sh"

    # Setup systemd timer for daily renewal check
    if command -v systemctl &> /dev/null && [ "$(id -u)" -eq 0 ]; then
        cat > /etc/systemd/system/arch-ssl-renewal.service << EOF
[Unit]
Description=Arch-Systems SSL Certificate Renewal
After=network.target docker.service

[Service]
Type=oneshot
User=$(who | awk '{print $1}')
ExecStart=$SCRIPT_DIR/renew-ssl.sh
EOF

        cat > /etc/systemd/system/arch-ssl-renewal.timer << EOF
[Unit]
Description=Daily SSL Certificate Renewal Check

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
EOF

        systemctl daemon-reload
        systemctl enable arch-ssl-renewal.timer
        systemctl start arch-ssl-renewal.timer

        log "Systemd timer created and enabled for daily renewal checks"
    else
        # Fallback to cron
        CRON_JOB="0 3 * * * $SCRIPT_DIR/renew-ssl.sh >> $LOG_FILE 2>&1"

        if ! crontab -l 2>/dev/null | grep -q "arch-ssl-renewal"; then
            (crontab -l 2>/dev/null | grep -v "arch-ssl-renewal"; echo "$CRON_JOB") | crontab -
            log "Cron job added for daily renewal checks (3 AM)"
        else
            log "Cron job already exists - skipping"
        fi
    fi

    # Test renewal script
    log "Testing renewal script..."
    "$SCRIPT_DIR/renew-ssl.sh" || warn "Renewal test failed (may be expected if cert is new)"
}

# ── Nginx Reload ─────────────────────────────────────────────────────────────
reload_nginx() {
    log "Reloading Nginx configuration..."

    if docker exec arch-nginx nginx -t 2>&1 | grep -q "successful"; then
        docker exec arch-nginx nginx -s reload
        log "Nginx reloaded successfully"
    else
        error "Nginx configuration test failed"
        docker exec arch-nginx nginx -t
        exit 1
    fi
}

# ── Verification ─────────────────────────────────────────────────────────────
verify_ssl() {
    local domain="$1"

    log "Verifying SSL certificate..."

    # Check certificate expiry
    echo | openssl s_client -servername "$domain" -connect "$domain:443" 2>/dev/null | \
        openssl x509 -noout -dates 2>/dev/null || {
            warn "Could not verify certificate via OpenSSL"
            return 0
        }

    # Check SSL Labs rating (optional, requires curl)
    if command -v curl &> /dev/null; then
        log "SSL Certificate obtained for $domain"
        log ""
        log "Next steps:"
        log "1. Verify site: https://$domain"
        log "2. Check SSL rating: https://www.ssllabs.com/ssltest/analyze.html?d=$domain"
        log "3. Monitor expiry: docker exec arch-certbot certbot certificates"
    fi
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
    local domain="${1:-}"
    local email="${2:-}"

    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     Arch-Systems SSL Certificate Setup                       ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo

    check_prerequisites "$domain" "$email"
    setup_directories
    create_nginx_ssl_config "$domain"

    echo
    log "Starting certificate acquisition for $domain..."
    echo

    obtain_certificate "$domain" "$email"
    setup_auto_renewal "$domain"
    reload_nginx
    verify_ssl "$domain"

    echo
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  ✅ SSL Setup Complete                                       ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo
    echo -e "Domain: ${CYAN}$domain${NC}"
    echo -e "Certificate: ${CYAN}$CERTS_DIR/$domain${NC}"
    echo -e "Expires: Check with ${CYAN}docker exec arch-certbot certbot certificates${NC}"
    echo
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
