// AUTO-GENERATED by tools/scripts/version-manager.mjs — DO NOT EDIT DIRECTLY
export const APP_VERSION = '1.6.2';
export const GIT_COMMIT_SHA = 'fc76279';
export const GIT_COMMIT_FULL = 'fc762790d0691cc0cf3692fac28f23db26be95d5';
export const GIT_BRANCH = 'main';
export const BUILD_TIMESTAMP = '2026-10-02T10:58:27.796Z';
export const RELEASE_NAME = 'Arch OS v1.6.2 // Industrial Command';
export const SYSTEM_CODENAME = 'Industrial Telemetry Bus';
