// AUTO-GENERATED by tools/scripts/version-manager.mjs — DO NOT EDIT DIRECTLY
export const APP_VERSION = '1.6.2';
export const GIT_COMMIT_SHA = '98bbeb9';
export const GIT_COMMIT_FULL = '98bbeb95895f4d496320e047ded554f2733d6c8c';
export const GIT_BRANCH = 'gitbutler/workspace';
export const BUILD_TIMESTAMP = '2026-10-08T05:33:48.721Z';
export const RELEASE_NAME = 'Arch OS v1.6.2 // Industrial Command';
export const SYSTEM_CODENAME = 'Industrial Telemetry Bus';
