/**
 * generated.ts — AUTO-GENERATED. DO NOT EDIT.
 *
 * Generated by: packages/theme/scripts/generate-tokens.mjs
 * Source:       packages/theme/src/css/variables.css
 *
 * Re-run with: node packages/theme/scripts/generate-tokens.mjs
 * Or via Turbo: pnpm --filter @repo/theme codegen
 *
 * This file provides typed `var(--token)` references for use in:
 * - Framer Motion style props
 * - Canvas/WebGL drawing
 * - Runtime style injection
 *
 * For static Tailwind usage, use the className utilities instead
 * (e.g. `text-[var(--text-heading)]` or `shadow-card`).
 */

export const tokens = {
  color: {
    bg: {
      buttonUiverse: 'var(--bg-button-uiverse)',
      buttonUiverseInner: 'var(--bg-button-uiverse-inner)',
    },
    border: {},
    text: {
      onGlass: 'var(--text-on-glass)',
      onGlassMuted: 'var(--text-on-glass-muted)',
      onGlassVideo: 'var(--text-on-glass-video)',
      onGlassVideoMuted: 'var(--text-on-glass-video-muted)',
      onDarkGlass: 'var(--text-on-dark-glass)',
      onDarkGlassMuted: 'var(--text-on-dark-glass-muted)',
    },
    accent: {
      blue: 'var(--accent-blue)',
      electricBlue: 'var(--accent-electric-blue)',
      electricBlueHover: 'var(--accent-electric-blue-hover)',
      electricBlueSubtle: 'var(--accent-electric-blue-subtle)',
      electricBlueBorder: 'var(--accent-electric-blue-border)',
      mint: 'var(--accent-mint)',
      mintHover: 'var(--accent-mint-hover)',
      mintSubtle: 'var(--accent-mint-subtle)',
      mintBorder: 'var(--accent-mint-border)',
      amber: 'var(--accent-amber)',
      amberHover: 'var(--accent-amber-hover)',
      amberSubtle: 'var(--accent-amber-subtle)',
      amberBorder: 'var(--accent-amber-border)',
      foreground: 'var(--accent-foreground)',
    },
    mac: {
      red: 'var(--mac-red)',
      yellow: 'var(--mac-yellow)',
      green: 'var(--mac-green)',
      menuBarHeight: 'var(--mac-menu-bar-height)',
    },
    glass: {
      surface: 'var(--glass-surface)',
      surfaceHover: 'var(--glass-surface-hover)',
      surfaceStrong: 'var(--glass-surface-strong)',
      border: 'var(--glass-border)',
      borderTop: 'var(--glass-border-top)',
      videoSurface: 'var(--glass-video-surface)',
      videoSurfaceHover: 'var(--glass-video-surface-hover)',
      videoSurfaceStrong: 'var(--glass-video-surface-strong)',
      videoBackdrop: 'var(--glass-video-backdrop)',
      videoBorder: 'var(--glass-video-border)',
      videoBorderBottom: 'var(--glass-video-border-bottom)',
      videoSheen: 'var(--glass-video-sheen)',
      videoShadow: 'var(--glass-video-shadow)',
      videoRadius: 'var(--glass-video-radius)',
      premiumBackdrop: 'var(--glass-premium-backdrop)',
      premiumBorder: 'var(--glass-premium-border)',
      premiumRadius: 'var(--glass-premium-radius)',
      borderSubtle: 'var(--glass-border-subtle)',
    },
    vibrancy: {
      surface: 'var(--vibrancy-surface)',
      border: 'var(--vibrancy-border)',
    },
  },
  primitives: {
    white: '#ffffff',
    archBrandBlue: '#007aff',
    archBrandBlueHover: '#0066eb',
  },
  hsl: {
    card: '0 0% 100%',
    popover: '0 0% 100%',
    primaryForeground: '0 0% 100%',
    accent: '240 5% 91%',
    accentForeground: '240 6% 10%',
    destructiveForeground: '0 0% 100%',
    chart1: '240 6% 10%',
    chart2: '142 71% 45%',
    chart3: '240 5% 45%',
    chart4: '3 78% 46%',
    chart5: '270 60% 55%',
  },
  shadow: {
    glowElectricBlue: 'var(--shadow-glow-electric-blue)',
    glowMint: 'var(--shadow-glow-mint)',
    glowAmber: 'var(--shadow-glow-amber)',
    diffusionSm: 'var(--shadow-diffusion-sm)',
    diffusionMd: 'var(--shadow-diffusion-md)',
    diffusionLg: 'var(--shadow-diffusion-lg)',
    diffusionXl: 'var(--shadow-diffusion-xl)',
    glowBlue: 'var(--shadow-glow-blue)',
    glowPrimary: 'var(--shadow-glow-primary)',
    glowElectric: 'var(--shadow-glow-electric)',
    buttonUiverseAfter: 'var(--shadow-button-uiverse-after)',
    buttonUiverseBlob: 'var(--shadow-button-uiverse-blob)',
    cirTabs: 'var(--shadow-cir-tabs)',
    cirCheckFocus: 'var(--shadow-cir-check-focus)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  radius: {},
  wave: {
    intensity: '0.2',
    speedMult: '0.5',
    amplScale: '0.4',
    opacity: '0.25',
  },
} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.color;
export type PrimitiveTokens = typeof tokens.primitives;
export type HslTokens = typeof tokens.hsl;
export type ShadowTokens = typeof tokens.shadow;
export type RadiusTokens = typeof tokens.radius;
